#!/bin/bash
_yadm_cfg_dir="$(dirname "${BASH_SOURCE:-$0}")"

cd "${HOME}" || return

mkdir -p ~/.local/bin
mkdir -p ~/.local/share

if [ "$(uname)" = "Linux" ]; then
    _distro_id=$(grep "^ID=" /etc/os-release | awk -F= '{print $2}')
    if [ "$_distro_id" = \""centos"\" ]; then
        [ -f ~/.config/yadm/rhel/bootstrap.sh ] && bash ~/.config/yadm/rhel/bootstrap.sh
    fi
    if [ "$_distro_id" = "fedora" ]; then
        [ -f ~/.config/yadm/fedora/bootstrap.sh ] && bash ~/.config/yadm/fedora/bootstrap.sh
    fi
    if [ "$_distro_id" = \""rhel"\" ]; then
        [ -f ~/.config/yadm/rhel/bootstrap.sh ] && bash ~/.config/yadm/rhel/bootstrap.sh
    fi
else
    echo "Assume windows for now..."
fi
