#!/bin/sh
_yadm_cfg_dir="$( dirname "${BASH_SOURCE[0]}" )"

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd ${HOME}

mkdir -p ~/.local/bin
mkdir -p ~/.local/share
# bash $_yadm_cfg_dir/nvim.sh
# bash $_yadm_cfg_dir/tmux.sh
# bash $_yadm_cfg_dir/rust.sh
# bash $_yadm_cfg_dir/go.sh
# bash $_yadm_cfg_dir/alacritty.sh
# bash $_yadm_cfg_dir/jbm_font.sh

if [ "$(uname)" = "Linux" ]; then
    _distro_id=$(grep "^ID=" /etc/os-release | awk -F= '{print $2}')
    if [ $_distro_id = "fedora" ]; then
        [ -f ~/.config/yadm/fedora/bootstrap.sh ] && bash ~/.config/yadm/fedora/bootstrap.sh
    fi
    if [ $_distro_id = "rhel" ]; then
        [ -f ~/.config/yadm/rhel/bootstrap.sh ] && bash ~/.config/yadm/rhel/bootstrap.sh
    fi
else
    echo "Assume windows for now..."
fi
