import = [
    "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMonoNL Nerd Font"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
